# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: me@sravankumar.co
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/"
url: "http://sravankumar.co"
twitter_username: sravancb
github_username:  mastersk3
facebook_username:  sravan.kumar2

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
